### ISSUE TITLE
Including plugin causes android app to crash

### ISSUE THREAD

**Issue by lowe0292** [lyonzy/nativescript-firebase#1]
After installing this plugin and requiring it in a component:

```
var Firebase = require('nativescript-firebase');
var firebase = new Firebase('https://my-firebase-name.firebaseio.com/');
```

my nativescript app errors:

```
java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
Fail to load module: /data/data/com.yourdomain.appname/files/app/app.js

TypeError: Cannot read property 'client' of undefined
File: "<unknown>, line: 1, column: 265

StackTrace: 
    Frame: function:'', file:'/data/data/com.yourdomain.appname/files/app/tns_modules/nativescript-websockets/websockets.js', line: 44, column: 36
    Frame: function:'require', file:'', line: 1, column: 266
    Frame: function:'', file:'/data/data/com.yourdomain.appname/files/app/tns_modules/nativescript-firebase/firebase.js', line: 1, column: 70
    Frame: function:'require', file:'', line: 1, column: 266
    Frame: function:'', file:'/data/data/com.yourdomain.appname/files/app/app/components/home/home.component.js', line: 16, column: 16
    Frame: function:'require', file:'', line: 1, column: 266
    Frame: function:'', file:'/data/data/com.yourdomain.appname/files/app/app/components/app/app.component.js', line: 21, column: 24
    Frame: function:'require', file:'', line: 1, column: 266
    Frame: function:'', file:'/data/data/com.yourdomain.appname/files/app/pages/app/app.component.js', line: 25, column: 23
    Frame: function:'require', file:'', line: 1, column: 266
    Frame: function:'', file:'/data/data/com.yourdomain.appname/files/app/app.js', line: 19, column: 23
    Frame: function:'require', file:'', line: 1, column: 266


    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5003)
    at android.app.ActivityThread.access$1600(ActivityThread.java:150)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1455)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:168)
    at android.app.ActivityThread.main(ActivityThread.java:5781)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
Caused by: com.tns.NativeScriptException: 
Fail to load module: /data/data/com.yourdomain.appname/files/app/app.js

TypeError: Cannot read property 'client' of undefined
File: "<unknown>, line: 1, column: 265

StackTrace: 
    Frame: function:'', file:'/data/data/com.yourdomain.appname/files/app/tns_modules/nativescript-websockets/websockets.js', line: 44, column: 36
    Frame: function:'require', file:'', line: 1, column: 266
    Frame: function:'', file:'/data/data/com.yourdomain.appname/files/app/tns_modules/nativescript-firebase/firebase.js', line: 1, column: 70
    Frame: function:'require', file:'', line: 1, column: 266
    Frame: function:'', file:'/data/data/com.yourdomain.appname/files/app/app/components/home/home.component.js', line: 16, column: 16
    Frame: function:'require', file:'', line: 1, column: 266
    Frame: function:'', file:'/data/data/com.yourdomain.appname/files/app/app/components/app/app.component.js', line: 21, column: 24
    Frame: function:'require', file:'', line: 1, column: 266
    Frame: function:'', file:'/data/data/com.yourdomain.appname/files/app/pages/app/app.component.js', line: 25, column: 23
    Frame: function:'require', file:'', line: 1, column: 266
    Frame: function:'', file:'/data/data/com.yourdomain.appname/files/app/app.js', line: 19, column: 23
    Frame: function:'require', file:'', line: 1, column: 266


    at com.tns.Runtime.runModule(Native Method)
    at com.tns.Runtime.runModule(Runtime.java:241)
    at com.tns.Runtime.run(Runtime.java:235)
    at com.tns.RuntimeHelper.initRuntime(RuntimeHelper.java:129)
    at com.tns.NativeScriptApplication.onCreate(NativeScriptApplication.java:13)
    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1026)
    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5000)
    ... 8 more
```

Any idea what I might have done wrong?

**Comment by fjflala** [comment]
I'm having the same issue. I added 'compile "org.java-websocket:Java-Websocket:1.3.0"', it worked, but now I'm having another exception "Failed to find module '_stream_writable'"

**Comment by armackey** [comment]
Same issue.
